package com.He.W.onebone.circuit.cu.component;

public enum EnumComponentType {
	
<<<<<<< HEAD
COMPONENT_ELECTRICITYBLOCKER, COMPONENT_RESISTER, COMPONENT_TRANSISTOR, COMPONENT_WIRE, COMPONENT_WIRETOCOG, COMPONENT_COGTOWIRE, COMPONENT_COG
=======
	COMPONENT_RESISTER, COMPONENT_TRANSISTOR, COMPONENT_WIRE, COMPONENT_WIRETOCOG, COMPONENT_COGTOWIRE
>>>>>>> 2709510a15f57237682fc870b661e5bcd0900f08

}
