package com.He.W.onebone.circuit.cu.component;

public enum EnumComponentType {
	
COMPONENT_ELECTRICITYBLOCKER, COMPONENT_RESISTER, COMPONENT_TRANSISTOR, COMPONENT_WIRE, COMPONENT_WIRETOCOG, COMPONENT_COGTOWIRE, COMPONENT_COG

}
