package com.He.W.onebone.circuit.cu.gamebase;

public enum EnumRotation {
ROTATE_TOP_BOTTOM, ROTATE_LEFT_RIGHT, ROTATE_TOP_RIGHT, ROTATE_TOP_LEFT, ROTATE_BOTTOM_RIGHT, ROTATE_BOTTOM_LEFT, SP_ROTATE_BOTTOM_TOP, SP_ROTATE_RIGHT_LEFT
}
